---
title: "Homework 9,  STAT 613"
author: "Norris Jaber"
date: "4/9/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus)
library(tidyverse)
library(dplyr)
library(ggplot2)
```
1.
```{r}
census_api_key("fafa6e7c431d63c5dec1875c21b22c0e7dbdbd71")
install = TRUE
```
2a.
```{r}
v15 <- load_variables(2015, "acs5", cache = TRUE)
View(v15) 
ca <- get_acs(geography = "county", 
              variables = c(medincome = "B01001A_011"), 
              state = "CA", 
              year = 2015)
mean(ca$moe)
median(ca$estimate)
ca
```
2b. 
```{r}
ca%>%
  filter(estimate > 30000)%>%
  arrange(desc(estimate)) -> ca1
ca1
```
2c.
```{r}
ca1%>%
  filter(estimate == 51644 & moe == 667)
```
2d.
```{r}
ca1 %>%
  ggplot(aes(x=estimate))+
  geom_boxplot(fill="red")
```
2e.
```{r}
ca1 %>%
  mutate(NAME = gsub(" County, California", "", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(color = "blue", size = 3) +
  labs(title = "Median Income for White Males by County",
       subtitle = "2014-2018 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)")
```

